export enum AuditAction {
  ORDER_CREATED = 'ORDER_CREATED',
  ORDER_STATUS_CHANGED = 'ORDER_STATUS_CHANGED',
  DELIVERY_SCHEDULED = 'DELIVERY_SCHEDULED',
  DELIVERY_RESCHEDULED = 'DELIVERY_RESCHEDULED',
  TRANSPORT_CHANGED = 'TRANSPORT_CHANGED',
}
